name: 'scp-remote-action'
description: 'use ssh channel,upload local file and directory to remote server ,or download file and directory from remote server'
branding:
  color: 'red'
  icon: 'chevron-up'
author: 'wenchui'
inputs:
  ipaddr: 
    required: true
    description: 'the remote server node ip address'
    default: '192.168.130.159'
  username: 
    required: true
    description: 'the remote server node login username'
    default: 'service'
  password: 
    required: true
    description: 'the remote server node login password,use github '
    default: '1234567890'
  operation_type: 
    required: true
    description: "upload or download,如果是upload,会将配置在前面的本地的文件上传到远端服务器,如果是download,会将配置在前面的远端文件下载到本地来"
    default: "upload"
  operation_list: 
    required: true
    description: 'upload or download file/dir list,file表示上传或下载文件,dir表示上传或者下载目录,请仔细填写确定路径存在且正确'
    default: |
             file /root/test/target/test.war /usr/local/tomcat/webapps/
             dir /root/testnode/dist/* /usr/local/wwww/server/node/
runs:
  using: 'node16'
  main: 'dist/index.js'
